defaults:
  # python biols_image_data.py --config defaults biols_image_learn_L --biols_data_folder er1-def_datagen_nofix_noise_no_interv_noise-chemdataproj-d005-D2500-multi-n_pairs2000-sets20-gaussianinterv --data_seed 0
  lr: 0.0001
  logdir: 'logs'
  min_interv_value: -5.
  max_interv_value: 5.
  log_stds_max: 5.0
  s_prior_std: 3.0
  posterior_samples: 64
  hidden_size: 128
  fixed_tau: 0.2
  logit_constraint: 10
  max_deviation: 0.01
  bethe_iters: 20
  learn_L: True
  dataset: 'vector'
  learn_Z: True
  learn_intervs: False
  datagen_type: 'weakly_supervised'
  interv_value_sampling: 'zeros'
  edge_threshold: 0.3
  baseroot: '/home/mila/j/jithendaraa.subramanian'
  biols_data_folder: 'er1-ws_datagen_fix_noise_interv_noise-linearproj-d005-D0100-multi-n_pairs2000-sets20-gaussianinterv'
  data_seed: 0
  num_steps: 10000
  wandb_project: 'BIOLS'
  wandb_entity: 'structurelearning'
  off_wandb: True
  learn_P: False
  pred_sigma: 0.1
  batch_size: 10000

  # ! Dont change this or remove
  clamp_low: -8.
  clamp_high: 8.

  # Remove later
  sem_type: 'linear-gauss'
  graph_type: 'erdos-renyi'

biols_learn_L:
  exp_name: 'BIOLS_learnL'
  num_steps: 10000
  learn_P: False

biols_image_learn_L:
  exp_name: 'BIOLS_Image_learnL'
  num_steps: 1000
  learn_P: False
  batch_size: 256
  lr: 0.001

biols_learn_P:
  exp_name: 'BIOLS_learnSCM'
  num_steps: 20000
  learn_P: True

biols_image_learn_P:
  exp_name: 'BIOLS_Image_learnL'
  num_steps: 20000
  learn_P: True

vae_linear_baseline:
  exp_name: 'VAE baseline'
  data_seed: 0
  num_steps: 10000
  corr: True

graphvae_vector_baseline:
  exp_name: 'GraphVAE (vector)'
  data_seed: 0
  biols_data_folder: 'er1-ws_datagen_fix_noise_interv_noise-SONproj-d005-D0005-multi-n_pairs2000-sets20-gaussianinterv'
  batch_size: 10000
  model_name: 'GraphVAE'
  loss: 'loss_MNIST'
  lr: 0.001
  step_size: 100
  gamma: 0.8
  dataset: 'vector'
  epochs: 200
  save_dir: "saved/"
  save_period: 50
  verbosity: 2
  monitor: off
  early_stop: 10000
  tensorboardX: False
  log_dir: "saved/runs"

gaussian_interv_sampling:
  interv_value_sampling: 'gaussian'

biols_fix_noise_interv_noise_single_interv_zerointerv:
  fix_noise: True
  no_interv_noise: False 
  biols_data_folder: 'er1-ws_datagen_fix_noise_interv_noise-SONproj-d005-D0005-single-n_pairs2000-sets20-zerosinterv-non_eq_noise_var'

biols_fix_noise_interv_noise_multi_interv_zerointerv:
  fix_noise: True
  no_interv_noise: False 
  biols_data_folder: 'er1-ws_datagen_fix_noise_interv_noise-SONproj-d005-D0005-single-n_pairs2000-sets20-zerosinterv-non_eq_noise_var'

biols_fix_noise_interv_noise_multi_interv_gaussian_interv:
  fix_noise: True
  no_interv_noise: False 
  biols_data_folder: 'er1-ws_datagen_nofix_noise_interv_noise-SONproj-d005-D0005-multi-n_pairs2000-sets20-gaussianinterv-non_eq_noise_var'

