create_dataset:
  exp_name: 'Create dataset'
  data_seed: 0
  min_interv_value: -5.
  max_interv_value: 5.
  interv_value_sampling: 'zeros'
  eq_noise_var: False
  dataset: 'vector'
  noise_sigma: 0.1
  decoder_sigma: 0.1
  sem_type: 'linear-gauss'
  baseroot: '/home/mila/j/jithendaraa.subramanian'
  edge_threshold: 0.3
  clamp_low: -8.
  clamp_high: 8.
  decoder_noise: True
  interv_noise_dist_sigma: 0.1
  interv_value_dist_sigma: 2.

nonlinear_scm:
  sem_type: 'nonlinear-gauss'

linear_scm:
  sem_type: 'linear-gauss'

d5:
  num_nodes: 5
  proj_dims: 100
  n_interv_sets: 20
  pts_per_interv: 100
  n_pairs: 2000

d10:
  num_nodes: 10
  proj_dims: 100
  n_interv_sets: 20
  pts_per_interv: 100
  n_pairs: 2000

d15:
  num_nodes: 15
  proj_dims: 100
  n_interv_sets: 20
  pts_per_interv: 100
  n_pairs: 2000

d20:
  num_nodes: 20
  proj_dims: 100
  n_interv_sets: 20
  pts_per_interv: 100
  n_pairs: 2000

d25:
  num_nodes: 25
  proj_dims: 100
  n_interv_sets: 20
  pts_per_interv: 100
  n_pairs: 2000


d30:
  num_nodes: 30
  proj_dims: 100
  n_interv_sets: 20
  pts_per_interv: 100
  n_pairs: 2000

d40:
  num_nodes: 40
  proj_dims: 100
  n_interv_sets: 20
  pts_per_interv: 100
  n_pairs: 2000

d50:
  num_nodes: 50
  proj_dims: 100
  n_interv_sets: 20
  pts_per_interv: 100
  n_pairs: 2000

d1000:
  num_nodes: 1000
  proj_dims: 2000
  n_interv_sets: 20
  pts_per_interv: 100
  n_pairs: 2000


son_d5:
  num_nodes: 5
  proj_dims: 5
  n_pairs: 2000
  n_interv_sets: 20
  pts_per_interv: 100
  proj: 'SON'

son_d10:
  num_nodes: 10
  proj_dims: 10
  n_pairs: 2000
  n_interv_sets: 20
  pts_per_interv: 100
  proj: 'SON'

linear_proj:
  proj: 'linear'

nonlinear_proj:
  proj: '3_layer_mlp'

chemdata_proj:
  proj: 'chemdata'
  proj_dims: 2500
  dataset: 'chemdata'
  interv_value_dist_sigma: 1.
  decoder_sigma: 0.05
  decoder_noise: True

default_datagen_decoder_noise:
  datagen_type: 'default'
  no_interv_noise: True
  fix_noise: False
  decoder_noise: True

default_datagen_no_decoder_noise:
  datagen_type: 'default'
  no_interv_noise: True
  fix_noise: False
  decoder_noise: False


# Exactly intervention value; noise for z1 and z2 is same
ws_datagen_no_interv_noise_fix_noise:
  datagen_type: 'weakly_supervised'
  no_interv_noise: True
  fix_noise: True
  decoder_noise: True

ws_datagen_no_interv_noise_nofix_noise:
  datagen_type: 'weakly_supervised'
  no_interv_noise: True
  fix_noise: False
  decoder_noise: True

# Intervention value + noise; noise for z1 and z2 is same
ws_datagen_interv_noise_fix_noise:
  datagen_type: 'weakly_supervised'
  no_interv_noise: False
  fix_noise: True
  decoder_noise: True

# Intervention value + noise; noise for z1 and z2 is not same
ws_datagen_interv_noise_nofix_noise:
  datagen_type: 'weakly_supervised'
  no_interv_noise: False
  fix_noise: False
  decoder_noise: True

er1: 
  exp_edges: 1.0
  graph_type: 'erdos-renyi'

er2: 
  exp_edges: 2.0
  graph_type: 'erdos-renyi'

er4: 
  exp_edges: 4.0
  graph_type: 'erdos-renyi'

single_interv:
  interv_type: 'single'

multi_interv:
  interv_type: 'multi'

zero_intervs:
  interv_value_sampling: 'zeros'

gaussian_intervs:
  interv_value_sampling: 'gaussian'

uniform_intervs:
  interv_value_sampling: 'uniform'

